# # Importo las librerias

In [1]:
import pandas as pd
import numpy as np
import os

## Leo el CSV

In [2]:
df=pd.read_csv(f'{os.getcwd()}/b_12_01_21.csv',
            sep=',',
            header=1,
            index_col=False,)

In [3]:
df.isnull().sum()

time                                  0
AN2L_BG00_Arm1_GatePos               11
AN2L_BG00_Arm2_GatePos               11
BG_OS1BP_1PB                         11
BG_OS1BP_2PB                         11
Heat Number                          11
AN2E_RAM_HMI_SteelGrade              11
AN2L_YO00_LadleWeight_Net_CastPos    11
AN2L_BG09BD1A                        11
AN2L_BG09BD1B                        11
Tiempo_Apertura_1                     9
Tiempo_Apertura_2                     9
T_Apertura_1                          9
T_Apertura_2                          9
AN2L_BA00_RotDrive_Position          11
Indice                                0
NumeroCucharaColando                 11
AN2L_BG09BD1A.1                      11
AN2L_BG09BD1B.1                      11
AN2L_BG09BD2A                        11
AN2L_BG09BD2B                        11
dtype: int64

In [4]:
limpio=df.interpolate()

In [5]:
limpio

,time,AN2L_BG00_Arm1_GatePos,AN2L_BG00_Arm2_GatePos,BG_OS1BP_1PB,BG_OS1BP_2PB,Heat Number,AN2E_RAM_HMI_SteelGrade,AN2L_YO00_LadleWeight_Net_CastPos,AN2L_BG09BD1A,AN2L_BG09BD1B,...,Tiempo_Apertura_2,T_Apertura_1,T_Apertura_2,AN2L_BA00_RotDrive_Position,Indice,NumeroCucharaColando,AN2L_BG09BD1A.1,AN2L_BG09BD1B.1,AN2L_BG09BD2A,AN2L_BG09BD2B
0,12.01.2021 12:28:34.947000,180.318,1.72502,0.0,0.0,170205.0,5.0,26.3360,32.9133,71.1317,...,0.0,0.0,0.0,180.0,0,20.0,32.9133,71.1317,2.33054,4.78091
1,12.01.2021 12:28:35.047000,180.318,1.72502,0.0,0.0,170205.0,5.0,26.3360,32.9133,71.1317,...,0.0,0.0,0.0,180.0,0,20.0,32.9133,71.1317,2.33054,4.78091
2,12.01.2021 12:28:35.147000,180.318,1.72502,0.0,0.0,170205.0,5.0,26.3167,32.9110,71.0291,...,0.0,0.0,0.0,180.0,0,20.0,32.9110,71.0291,2.32993,4.76205
3,12.01.2021 12:28:35.247000,180.318,1.72502,0.0,0.0,170205.0,5.0,26.3167,32.9110,71.0291,...,0.0,0.0,0.0,180.0,0,20.0,32.9110,71.0291,2.32993,4.76205
4,12.01.2021 12:28:35.347000,180.318,1.78987,0.0,0.0,170205.0,5.0,26.3167,32.9099,70.9221,...,0.0,0.0,0.0,180.0,0,20.0,32.9099,70.9221,2.33252,4.78058
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432004,13.01.2021 00:28:35.347000,166.284,8.77431,0.0,0.0,180205.0,2.0,29.7245,18.4272,46.7383,...,0.0,0.0,0.0,180.0,20,19.0,18.4272,46.7383,6.73999,10.77150
432005,13.01.2021 00:28:35.447000,166.349,8.77431,0.0,0.0,180205.0,2.0,29.6798,18.5621,46.5938,...,0.0,0.0,0.0,180.0,20,19.0,18.5621,46.5938,6.78937,10.92410
432006,13.01.2021 00:28:35.547000,166.349,8.77431,0.0,0.0,180205.0,2.0,29.6798,18.5621,46.5938,...,0.0,0.0,0.0,180.0,20,19.0,18.5621,46.5938,6.78937,10.92410
432007,13.01.2021 00:28:35.647000,166.284,8.77431,0.0,0.0,180205.0,2.0,29.6798,18.5671,46.4301,...,0.0,0.0,0.0,180.0,20,19.0,18.5671,46.4301,6.74771,10.67240
432008,13.01.2021 00:28:35.747000,166.284,8.77431,0.0,0.0,180205.0,2.0,29.6798,18.5694,46.4978,...,0.0,0.0,0.0,180.0,20,19.0,18.5694,46.4978,6.75040,10.75160

In [6]:
limpio.isnull().sum()

time                                 0
AN2L_BG00_Arm1_GatePos               0
AN2L_BG00_Arm2_GatePos               0
BG_OS1BP_1PB                         0
BG_OS1BP_2PB                         0
Heat Number                          0
AN2E_RAM_HMI_SteelGrade              0
AN2L_YO00_LadleWeight_Net_CastPos    0
AN2L_BG09BD1A                        0
AN2L_BG09BD1B                        0
Tiempo_Apertura_1                    0
Tiempo_Apertura_2                    0
T_Apertura_1                         0
T_Apertura_2                         0
AN2L_BA00_RotDrive_Position          0
Indice                               0
NumeroCucharaColando                 0
AN2L_BG09BD1A.1                      0
AN2L_BG09BD1B.1                      0
AN2L_BG09BD2A                        0
AN2L_BG09BD2B                        0
dtype: int64

In [7]:
apertura=pd.DataFrame(limpio,columns=['NumeroCucharaColando','Heat Number','Tiempo_Apertura_1','Tiempo_Apertura_2'])

In [8]:
apertura.corr()

,NumeroCucharaColando,Heat Number,Tiempo_Apertura_1,Tiempo_Apertura_2
NumeroCucharaColando,1.000000,0.440930,-0.009688,0.014873
Heat Number,0.440930,1.000000,-0.026243,0.023065
Tiempo_Apertura_1,-0.009688,-0.026243,1.000000,-0.000724
Tiempo_Apertura_2,0.014873,0.023065,-0.000724,1.000000

In [61]:
apertura_pivot = apertura.pivot_table(values=['Tiempo_Apertura_1','Tiempo_Apertura_2'],
                     index=['NumeroCucharaColando','Heat Number'],
                     aggfunc={'Tiempo_Apertura_1': np.max,
                              'Tiempo_Apertura_2': np.max})

In [62]:
apertura_pivot[(apertura_pivot['Tiempo_Apertura_1'] != 0) | (apertura_pivot['Tiempo_Apertura_2'] !=0)][1:] # [1:] Filtra "NumeroCucharaColando" != 0

                                  Tiempo_Apertura_1  Tiempo_Apertura_2
NumeroCucharaColando Heat Number
1.0                  170206.0                 3.220              0.000
                     170209.0                 3.015              0.000
                     170212.0                 3.115              0.000
                     170215.0                 3.315              0.000
7.0                  170207.0                 2.915              0.000
12.0                 180200.0                 0.000              2.985
                     180203.0                 0.000              2.805
15.0                 170208.0                 3.515              0.000
                     170211.0                 3.015              0.000
                     170214.0                 3.115              0.000
17.0                 170210.0                 3.115              0.000
                     170213.0                 4.025              0.000
19.0                 180196.0                 0.000              3.035
                     180199.0                 0.000              2.615
                     180202.0                 0.000              2.715
20.0                 170205.0                 0.000              2.845
                     180198.0                 0.000              3.495
                     180201.0                 0.000              4.015
                     180204.0                 0.000              3.420